// Create two functions

export default {
  // 1 drop users table
  dropUsersTable: () => {
    const queryString = 'DROP TABLE IF EXISTS users';
    return queryString;
  },

  // 2 create users table
  createUsersTable: () => {
    const queryString = `CREATE TABLE users (id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1),
                                              first_name varchar(255),
                                              last_name varchar(255),
                                              username varchar(255),
                                              email varchar(255),
                                              is_admin boolean,
                                              password varchar(255),
                                              CONSTRAINT users_pkey PRIMARY KEY (id))`;
    return queryString;
  },
};
