export default {
  dropBusesTable: () => {
    const queryString = 'DROP TABLE IF EXISTS buses';
    return queryString;
  },

  createBusesTable: () => {
    const queryString = `CREATE TABLE buses ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 ),
                                              number_plate varchar(255),
                                              manufacturer varchar(255),
                                              model varchar(255),
                                              year varchar(255),
                                              capacity INTEGER,
                                              CONSTRAINT buses_pkey PRIMARY KEY (id))`;
    return queryString;
  },
};
